### ISSUE TITLE
Add Empty State

### ISSUE THREAD

**Issue by AaronRietschlin** [blanyal/Remindly#32]
When there are no reminders set (for example when opening the app for the first time), it is just a blank screen. It would probably be a good idea to add some sort of empty state. Either an image or some sort of text that indicates that the user should click the FAB to create a Reminder.

**Comment by blanyal** [comment]
Added a text view instructing users to click the FAB when there are no reminders set.
Thanks for the feedback!

![device-2015-05-06-133748](https://cloud.githubusercontent.com/assets/8809901/7489515/3a554a24-f3f5-11e4-84a0-494a582c4d06.png)
