### ISSUE TITLE
Missing Zero when time is set on the hour

### ISSUE THREAD

**Issue by AaronRietschlin** [blanyal/Remindly#33]
If you set the time to the bottom of the hour (for example, set it to 9:00 am), it is missing a zero. See attached screenshot: 

![Screenshot of bug](http://i.imgur.com/ZyhdRtR.png)

**Comment by blanyal** [comment]
Thanks for the feedback. Fixed this issue. 

![device-2015-05-05-200410](https://cloud.githubusercontent.com/assets/8809901/7474852/9adc7f14-f361-11e4-9ab5-9c27ff4ad2ad.png)
